Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -98,6 +98,25 @@ jobs:
 
             - name: Test
               run: gradle test && gradle jacocoTestReport
+              continue-on-error: true
+
+            - name: Archive test reports if tests fail
+              if: failure()
+              run: |
+                zip -r test-reports.zip build/reports/tests/test
+                echo "##[error]Tests failed, see the report"
+              continue-on-error: false 
+
+            - name: Upload Test Reports
+              if: failure()
+              uses: actions/upload-artifact@v3
+              with:
+                name: test-reports
+                path: test-reports.zip
+
+            - name: Fail the job if tests failed
+              if: failure()
+              run: exit 1
             
             - name: Codecov
               run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
